........................................................................................F.F............E..........FE.....FFF....................
======================================================================
ERROR: test_search_arg_function_scalar_binop_scalar (__main__.RemesPathTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mjols\Python39\remespath\remespath\parser.py", line 1295, in test_search_arg_function_scalar_binop_scalar
    self.assertEqual(search("sum(@) / 4", [1, 3]), 1.0)
  File "C:\Users\mjols\Python39\remespath\remespath\parser.py", line 756, in search
    return resval(obj)
  File "C:\Users\mjols\Python39\remespath\remespath\parser.py", line 274, in <lambda>
    out = cur_json(lambda obj: binop_json_scalar(binop, aval(obj), bval))
  File "C:\Users\mjols\Python39\remespath\remespath\parser.py", line 255, in binop_json_scalar
    return [func(v, s) for v in j]
TypeError: 'int' object is not iterable

======================================================================
ERROR: test_search_dot_parens_idx (__main__.RemesPathTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mjols\Python39\remespath\remespath\parser.py", line 1400, in test_search_dot_parens_idx
    self.assertEqual(search("(@.foo)[0]", {'foo': [1,2], 'bar': 'a'}), 1)
  File "C:\Users\mjols\Python39\remespath\remespath\parser.py", line 756, in search
    return resval(obj)
  File "C:\Users\mjols\Python39\remespath\remespath\parser.py", line 559, in <lambda>
    result = lambda obj: apply_indexer_list(idxrs)(obj)
  File "C:\Users\mjols\Python39\remespath\remespath\parser.py", line 221, in <lambda>
    return lambda obj: outfunc(obj, indexers)
  File "C:\Users\mjols\Python39\remespath\remespath\parser.py", line 182, in outfunc
    result = idxr(obj)
  File "C:\Users\mjols\Python39\remespath\remespath\parser.py", line 141, in <lambda>
    return lambda x: outfunc(x, inds)
  File "C:\Users\mjols\Python39\remespath\remespath\parser.py", line 137, in outfunc
    out.append(x[k])
KeyError: 0

======================================================================
FAIL: test_projection_arr_parens_then_idx (__main__.RemesPathTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mjols\Python39\remespath\remespath\parser.py", line 1433, in test_projection_arr_parens_then_idx
    self.assertEqual(search("(@[:]{@.foo, @.bar})[1]", [{'foo': 1, 'bar': 3}, {'foo': 2, 'bar': 1}]), [2, 1])
AssertionError: {'foo': 2, 'bar': 1} != [2, 1]

======================================================================
FAIL: test_projection_obj_parens_then_dot (__main__.RemesPathTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mjols\Python39\remespath\remespath\parser.py", line 1439, in test_projection_obj_parens_then_dot
    self.assertEqual(search("(@{foo: @[0], bar: @[1]}).foo", [1,2]), 1)
AssertionError: {} != 1

======================================================================
FAIL: test_search_dot_parens_dot (__main__.RemesPathTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mjols\Python39\remespath\remespath\parser.py", line 1403, in test_search_dot_parens_dot
    self.assertEqual(search('(@.foo).bar', {'foo': {'bar': 1}}), 1)
AssertionError: {} != 1

======================================================================
FAIL: test_search_idx_on_expr_function (__main__.RemesPathTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mjols\Python39\remespath\remespath\parser.py", line 1375, in test_search_idx_on_expr_function
    self.assertEqual(search("sorted(@)[0]", [2, 1]), 1)
AssertionError: 2 != 1

======================================================================
FAIL: test_search_idx_parens_dot (__main__.RemesPathTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mjols\Python39\remespath\remespath\parser.py", line 1406, in test_search_idx_parens_dot
    self.assertEqual(search('(@[0]).a', [{'a': 1, 'b': 2}, {'a': 3, 'b': 4}]), 2)
AssertionError: {} != 2

======================================================================
FAIL: test_search_idx_parens_idx (__main__.RemesPathTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mjols\Python39\remespath\remespath\parser.py", line 1409, in test_search_idx_parens_idx
    self.assertEqual(search('(@[:1])[1:]', [[1,2],[3,4]]), [[2]])
AssertionError: Lists differ: [[3, 4]] != [[2]]

First differing element 0:
[3, 4]
[2]

- [[3, 4]]
+ [[2]]

----------------------------------------------------------------------
Ran 144 tests in 0.024s

FAILED (failures=6, errors=2)